### ISSUE TITLE
word.strip()

### ISSUE THREAD

**Issue by doublex** [Jeronymous/whisper-timestamped#3]
`whisper-timestamped` strips all words calling `xx.strip()`.
`whisper` works quite well with e.g. "scriptio continua".
If one removes the `xx.strip()` everything works as expected (getting the leading spaces).

**Comment by Jeronymous** [comment]
Could you please make the request clearer?

You want a leading space in front of each word in the dict returned by transcribe / json returned by the CLI?
As in the following example?
```
{
  "text": " I am here",
  "segments": [
    {
      "text": " I am here",
      ...
      "words": [
        {
          "text": " I", # <- leading space added here
          "start": 0.18,
          "end": 0.64
        },
        {
          "text": " am", # <- leading space added here
          "start": 0.64,
          "end": 1.02
        },
        {
          "text": " here", # <- leading space added here
          "start": 1.02,
          "end": 1.48
        }

      ]
    }
  ],
  ...
}
```
Can you give a minimal use of "scriptio continua" to see that?

**Comment by Jeronymous** [comment]
OK. You're welcome.
You can click a star on this project if you find it useful ;)
