### ISSUE TITLE
 Preparing metadata (setup.py)

### ISSUE THREAD

**Issue by romanzoniit** [Jeronymous/whisper-timestamped#8]
I'm trying to upload with pip your project and I get errors.
Please fix it

`pip3 install git+https://github.com/Jeronymous/whisper-timestamped`

![image](https://user-images.githubusercontent.com/71592522/213170396-802d6747-d872-4aeb-a5f6-3cce287803d5.png)

**Comment by Jeronymous** [comment]
Thanks for pinging on that.
`whisper` finally changed the package name to `openai-whisper` (because there was already a whisper package before, and that conflict gave me some hard times already).
This is fixed now.
Enjoy whisper-timestamped :)
